-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ArticleAlternativeQuantity
module WeclappAPI.Types.ArticleAlternativeQuantity where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.articleAlternativeQuantity@ in the specification.
-- 
-- 
data ArticleAlternativeQuantity = ArticleAlternativeQuantity {
  -- | createdDate
  articleAlternativeQuantityCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | id
  , articleAlternativeQuantityId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , articleAlternativeQuantityLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | minimumOrderQuantity
  , articleAlternativeQuantityMinimumOrderQuantity :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | minimumStockQuantity
  , articleAlternativeQuantityMinimumStockQuantity :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | targetStockQuantity
  , articleAlternativeQuantityTargetStockQuantity :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | version
  , articleAlternativeQuantityVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | warehouseId
  , articleAlternativeQuantityWarehouseId :: Data.Text.Internal.Text
  -- | warehouseName
  , articleAlternativeQuantityWarehouseName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ArticleAlternativeQuantity
    where toJSON obj = Data.Aeson.Types.Internal.object ("createdDate" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityCreatedDate obj : "id" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityLastModifiedDate obj : "minimumOrderQuantity" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityMinimumOrderQuantity obj : "minimumStockQuantity" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityMinimumStockQuantity obj : "targetStockQuantity" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityTargetStockQuantity obj : "version" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityVersion obj : "warehouseId" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityWarehouseId obj : "warehouseName" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityWarehouseName obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("createdDate" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityCreatedDate obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityLastModifiedDate obj) GHC.Base.<> (("minimumOrderQuantity" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityMinimumOrderQuantity obj) GHC.Base.<> (("minimumStockQuantity" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityMinimumStockQuantity obj) GHC.Base.<> (("targetStockQuantity" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityTargetStockQuantity obj) GHC.Base.<> (("version" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityVersion obj) GHC.Base.<> (("warehouseId" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityWarehouseId obj) GHC.Base.<> ("warehouseName" Data.Aeson.Types.ToJSON..= articleAlternativeQuantityWarehouseName obj)))))))))
instance Data.Aeson.Types.FromJSON.FromJSON ArticleAlternativeQuantity
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "ArticleAlternativeQuantity" (\obj -> ((((((((GHC.Base.pure ArticleAlternativeQuantity GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "minimumOrderQuantity")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "minimumStockQuantity")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "targetStockQuantity")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "warehouseId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "warehouseName"))
-- | Create a new 'ArticleAlternativeQuantity' with all required fields.
mkArticleAlternativeQuantity :: Data.Text.Internal.Text -- ^ 'articleAlternativeQuantityWarehouseId'
  -> ArticleAlternativeQuantity
mkArticleAlternativeQuantity articleAlternativeQuantityWarehouseId = ArticleAlternativeQuantity{articleAlternativeQuantityCreatedDate = GHC.Maybe.Nothing,
                                                                                                articleAlternativeQuantityId = GHC.Maybe.Nothing,
                                                                                                articleAlternativeQuantityLastModifiedDate = GHC.Maybe.Nothing,
                                                                                                articleAlternativeQuantityMinimumOrderQuantity = GHC.Maybe.Nothing,
                                                                                                articleAlternativeQuantityMinimumStockQuantity = GHC.Maybe.Nothing,
                                                                                                articleAlternativeQuantityTargetStockQuantity = GHC.Maybe.Nothing,
                                                                                                articleAlternativeQuantityVersion = GHC.Maybe.Nothing,
                                                                                                articleAlternativeQuantityWarehouseId = articleAlternativeQuantityWarehouseId,
                                                                                                articleAlternativeQuantityWarehouseName = GHC.Maybe.Nothing}
