module WeclappAPI.Types.ArticlePriceWithoutArticleReference where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data ArticlePriceWithoutArticleReference
instance Show ArticlePriceWithoutArticleReference
instance Eq ArticlePriceWithoutArticleReference
instance FromJSON ArticlePriceWithoutArticleReference
instance ToJSON ArticlePriceWithoutArticleReference
data ArticlePriceWithoutArticleReferencePriceScaleType'
instance Show ArticlePriceWithoutArticleReferencePriceScaleType'
instance Eq ArticlePriceWithoutArticleReferencePriceScaleType'
instance FromJSON ArticlePriceWithoutArticleReferencePriceScaleType'
instance ToJSON ArticlePriceWithoutArticleReferencePriceScaleType'
