-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema BillOfMaterial
module WeclappAPI.Types.BillOfMaterial where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.billOfMaterial@ in the specification.
-- 
-- 
data BillOfMaterial = BillOfMaterial {
  -- | articleId
  billOfMaterialArticleId :: Data.Text.Internal.Text
  -- | articleNumber
  , billOfMaterialArticleNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | createdDate
  , billOfMaterialCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | id
  , billOfMaterialId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , billOfMaterialLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | positionNumber
  , billOfMaterialPositionNumber :: (GHC.Maybe.Maybe GHC.Int.Int32)
  -- | quantity
  , billOfMaterialQuantity :: Data.Text.Internal.Text
  -- | version
  , billOfMaterialVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON BillOfMaterial
    where toJSON obj = Data.Aeson.Types.Internal.object ("articleId" Data.Aeson.Types.ToJSON..= billOfMaterialArticleId obj : "articleNumber" Data.Aeson.Types.ToJSON..= billOfMaterialArticleNumber obj : "createdDate" Data.Aeson.Types.ToJSON..= billOfMaterialCreatedDate obj : "id" Data.Aeson.Types.ToJSON..= billOfMaterialId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= billOfMaterialLastModifiedDate obj : "positionNumber" Data.Aeson.Types.ToJSON..= billOfMaterialPositionNumber obj : "quantity" Data.Aeson.Types.ToJSON..= billOfMaterialQuantity obj : "version" Data.Aeson.Types.ToJSON..= billOfMaterialVersion obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("articleId" Data.Aeson.Types.ToJSON..= billOfMaterialArticleId obj) GHC.Base.<> (("articleNumber" Data.Aeson.Types.ToJSON..= billOfMaterialArticleNumber obj) GHC.Base.<> (("createdDate" Data.Aeson.Types.ToJSON..= billOfMaterialCreatedDate obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= billOfMaterialId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= billOfMaterialLastModifiedDate obj) GHC.Base.<> (("positionNumber" Data.Aeson.Types.ToJSON..= billOfMaterialPositionNumber obj) GHC.Base.<> (("quantity" Data.Aeson.Types.ToJSON..= billOfMaterialQuantity obj) GHC.Base.<> ("version" Data.Aeson.Types.ToJSON..= billOfMaterialVersion obj))))))))
instance Data.Aeson.Types.FromJSON.FromJSON BillOfMaterial
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "BillOfMaterial" (\obj -> (((((((GHC.Base.pure BillOfMaterial GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "articleId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "articleNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "positionNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "quantity")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version"))
-- | Create a new 'BillOfMaterial' with all required fields.
mkBillOfMaterial :: Data.Text.Internal.Text -- ^ 'billOfMaterialArticleId'
  -> Data.Text.Internal.Text -- ^ 'billOfMaterialQuantity'
  -> BillOfMaterial
mkBillOfMaterial billOfMaterialArticleId billOfMaterialQuantity = BillOfMaterial{billOfMaterialArticleId = billOfMaterialArticleId,
                                                                                 billOfMaterialArticleNumber = GHC.Maybe.Nothing,
                                                                                 billOfMaterialCreatedDate = GHC.Maybe.Nothing,
                                                                                 billOfMaterialId = GHC.Maybe.Nothing,
                                                                                 billOfMaterialLastModifiedDate = GHC.Maybe.Nothing,
                                                                                 billOfMaterialPositionNumber = GHC.Maybe.Nothing,
                                                                                 billOfMaterialQuantity = billOfMaterialQuantity,
                                                                                 billOfMaterialVersion = GHC.Maybe.Nothing}
