-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema CostCenterWithDistributionPercentage
module WeclappAPI.Types.CostCenterWithDistributionPercentage where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.costCenterWithDistributionPercentage@ in the specification.
-- 
-- 
data CostCenterWithDistributionPercentage = CostCenterWithDistributionPercentage {
  -- | costCenterId
  costCenterWithDistributionPercentageCostCenterId :: Data.Text.Internal.Text
  -- | costCenterNumber
  , costCenterWithDistributionPercentageCostCenterNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | createdDate
  , costCenterWithDistributionPercentageCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | distributionPercentage
  , costCenterWithDistributionPercentageDistributionPercentage :: Data.Text.Internal.Text
  -- | id
  , costCenterWithDistributionPercentageId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , costCenterWithDistributionPercentageLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | version
  , costCenterWithDistributionPercentageVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CostCenterWithDistributionPercentage
    where toJSON obj = Data.Aeson.Types.Internal.object ("costCenterId" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageCostCenterId obj : "costCenterNumber" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageCostCenterNumber obj : "createdDate" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageCreatedDate obj : "distributionPercentage" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageDistributionPercentage obj : "id" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageLastModifiedDate obj : "version" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageVersion obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("costCenterId" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageCostCenterId obj) GHC.Base.<> (("costCenterNumber" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageCostCenterNumber obj) GHC.Base.<> (("createdDate" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageCreatedDate obj) GHC.Base.<> (("distributionPercentage" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageDistributionPercentage obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageLastModifiedDate obj) GHC.Base.<> ("version" Data.Aeson.Types.ToJSON..= costCenterWithDistributionPercentageVersion obj)))))))
instance Data.Aeson.Types.FromJSON.FromJSON CostCenterWithDistributionPercentage
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "CostCenterWithDistributionPercentage" (\obj -> ((((((GHC.Base.pure CostCenterWithDistributionPercentage GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "costCenterId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "costCenterNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "distributionPercentage")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version"))
-- | Create a new 'CostCenterWithDistributionPercentage' with all required fields.
mkCostCenterWithDistributionPercentage :: Data.Text.Internal.Text -- ^ 'costCenterWithDistributionPercentageCostCenterId'
  -> Data.Text.Internal.Text -- ^ 'costCenterWithDistributionPercentageDistributionPercentage'
  -> CostCenterWithDistributionPercentage
mkCostCenterWithDistributionPercentage costCenterWithDistributionPercentageCostCenterId costCenterWithDistributionPercentageDistributionPercentage = CostCenterWithDistributionPercentage{costCenterWithDistributionPercentageCostCenterId = costCenterWithDistributionPercentageCostCenterId,
                                                                                                                                                                                          costCenterWithDistributionPercentageCostCenterNumber = GHC.Maybe.Nothing,
                                                                                                                                                                                          costCenterWithDistributionPercentageCreatedDate = GHC.Maybe.Nothing,
                                                                                                                                                                                          costCenterWithDistributionPercentageDistributionPercentage = costCenterWithDistributionPercentageDistributionPercentage,
                                                                                                                                                                                          costCenterWithDistributionPercentageId = GHC.Maybe.Nothing,
                                                                                                                                                                                          costCenterWithDistributionPercentageLastModifiedDate = GHC.Maybe.Nothing,
                                                                                                                                                                                          costCenterWithDistributionPercentageVersion = GHC.Maybe.Nothing}
