module WeclappAPI.Types.CustomAttributeDefinitionLabel where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data CustomAttributeDefinitionLabel
instance Show CustomAttributeDefinitionLabel
instance Eq CustomAttributeDefinitionLabel
instance FromJSON CustomAttributeDefinitionLabel
instance ToJSON CustomAttributeDefinitionLabel
