module WeclappAPI.Types.CustomAttributeDefinitionListValue where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data CustomAttributeDefinitionListValue
instance Show CustomAttributeDefinitionListValue
instance Eq CustomAttributeDefinitionListValue
instance FromJSON CustomAttributeDefinitionListValue
instance ToJSON CustomAttributeDefinitionListValue
