-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Document
module WeclappAPI.Types.Document where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias
import {-# SOURCE #-} WeclappAPI.Types.DocumentVersion

-- | Defines the object schema located at @components.schemas.document@ in the specification.
-- 
-- 
data Document = Document {
  -- | createdDate
  documentCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | description
  , documentDescription :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id
  , documentId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , documentLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | mediaType
  , documentMediaType :: Data.Text.Internal.Text
  -- | name
  , documentName :: Data.Text.Internal.Text
  -- | userId
  , documentUserId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | version
  , documentVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | versions
  , documentVersions :: (GHC.Maybe.Maybe ([DocumentVersion]))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Document
    where toJSON obj = Data.Aeson.Types.Internal.object ("createdDate" Data.Aeson.Types.ToJSON..= documentCreatedDate obj : "description" Data.Aeson.Types.ToJSON..= documentDescription obj : "id" Data.Aeson.Types.ToJSON..= documentId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= documentLastModifiedDate obj : "mediaType" Data.Aeson.Types.ToJSON..= documentMediaType obj : "name" Data.Aeson.Types.ToJSON..= documentName obj : "userId" Data.Aeson.Types.ToJSON..= documentUserId obj : "version" Data.Aeson.Types.ToJSON..= documentVersion obj : "versions" Data.Aeson.Types.ToJSON..= documentVersions obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("createdDate" Data.Aeson.Types.ToJSON..= documentCreatedDate obj) GHC.Base.<> (("description" Data.Aeson.Types.ToJSON..= documentDescription obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= documentId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= documentLastModifiedDate obj) GHC.Base.<> (("mediaType" Data.Aeson.Types.ToJSON..= documentMediaType obj) GHC.Base.<> (("name" Data.Aeson.Types.ToJSON..= documentName obj) GHC.Base.<> (("userId" Data.Aeson.Types.ToJSON..= documentUserId obj) GHC.Base.<> (("version" Data.Aeson.Types.ToJSON..= documentVersion obj) GHC.Base.<> ("versions" Data.Aeson.Types.ToJSON..= documentVersions obj)))))))))
instance Data.Aeson.Types.FromJSON.FromJSON Document
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Document" (\obj -> ((((((((GHC.Base.pure Document GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "mediaType")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "userId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "versions"))
-- | Create a new 'Document' with all required fields.
mkDocument :: Data.Text.Internal.Text -- ^ 'documentMediaType'
  -> Data.Text.Internal.Text -- ^ 'documentName'
  -> Document
mkDocument documentMediaType documentName = Document{documentCreatedDate = GHC.Maybe.Nothing,
                                                     documentDescription = GHC.Maybe.Nothing,
                                                     documentId = GHC.Maybe.Nothing,
                                                     documentLastModifiedDate = GHC.Maybe.Nothing,
                                                     documentMediaType = documentMediaType,
                                                     documentName = documentName,
                                                     documentUserId = GHC.Maybe.Nothing,
                                                     documentVersion = GHC.Maybe.Nothing,
                                                     documentVersions = GHC.Maybe.Nothing}
