-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema FastProductionBookingResult
module WeclappAPI.Types.FastProductionBookingResult where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.fastProductionBookingResult@ in the specification.
-- 
-- 
data FastProductionBookingResult = FastProductionBookingResult {
  -- | message
  fastProductionBookingResultMessage :: (GHC.Maybe.Maybe FastProductionBookingResultMessage')
  -- | success
  , fastProductionBookingResultSuccess :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON FastProductionBookingResult
    where toJSON obj = Data.Aeson.Types.Internal.object ("message" Data.Aeson.Types.ToJSON..= fastProductionBookingResultMessage obj : "success" Data.Aeson.Types.ToJSON..= fastProductionBookingResultSuccess obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("message" Data.Aeson.Types.ToJSON..= fastProductionBookingResultMessage obj) GHC.Base.<> ("success" Data.Aeson.Types.ToJSON..= fastProductionBookingResultSuccess obj))
instance Data.Aeson.Types.FromJSON.FromJSON FastProductionBookingResult
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "FastProductionBookingResult" (\obj -> (GHC.Base.pure FastProductionBookingResult GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "message")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "success"))
-- | Create a new 'FastProductionBookingResult' with all required fields.
mkFastProductionBookingResult :: FastProductionBookingResult
mkFastProductionBookingResult = FastProductionBookingResult{fastProductionBookingResultMessage = GHC.Maybe.Nothing,
                                                            fastProductionBookingResultSuccess = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.fastProductionBookingResult.properties.message@ in the specification.
-- 
-- 
data FastProductionBookingResultMessage' =
   FastProductionBookingResultMessage'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | FastProductionBookingResultMessage'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | FastProductionBookingResultMessage'EnumINVALID_ORDER -- ^ Represents the JSON value @"INVALID_ORDER"@
  | FastProductionBookingResultMessage'EnumINVALID_ORDER_NUMBER -- ^ Represents the JSON value @"INVALID_ORDER_NUMBER"@
  | FastProductionBookingResultMessage'EnumINVALID_QUANTITY -- ^ Represents the JSON value @"INVALID_QUANTITY"@
  | FastProductionBookingResultMessage'EnumSUCCESS -- ^ Represents the JSON value @"SUCCESS"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON FastProductionBookingResultMessage'
    where toJSON (FastProductionBookingResultMessage'Other val) = val
          toJSON (FastProductionBookingResultMessage'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (FastProductionBookingResultMessage'EnumINVALID_ORDER) = "INVALID_ORDER"
          toJSON (FastProductionBookingResultMessage'EnumINVALID_ORDER_NUMBER) = "INVALID_ORDER_NUMBER"
          toJSON (FastProductionBookingResultMessage'EnumINVALID_QUANTITY) = "INVALID_QUANTITY"
          toJSON (FastProductionBookingResultMessage'EnumSUCCESS) = "SUCCESS"
instance Data.Aeson.Types.FromJSON.FromJSON FastProductionBookingResultMessage'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "INVALID_ORDER" -> FastProductionBookingResultMessage'EnumINVALID_ORDER
                                            | val GHC.Classes.== "INVALID_ORDER_NUMBER" -> FastProductionBookingResultMessage'EnumINVALID_ORDER_NUMBER
                                            | val GHC.Classes.== "INVALID_QUANTITY" -> FastProductionBookingResultMessage'EnumINVALID_QUANTITY
                                            | val GHC.Classes.== "SUCCESS" -> FastProductionBookingResultMessage'EnumSUCCESS
                                            | GHC.Base.otherwise -> FastProductionBookingResultMessage'Other val)
