-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Notification
module WeclappAPI.Types.Notification where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.notification@ in the specification.
-- 
-- 
data Notification = Notification {
  -- | createdDate
  notificationCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | description
  , notificationDescription :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id
  , notificationId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , notificationLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | read
  , notificationRead :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | title
  , notificationTitle :: Data.Text.Internal.Text
  -- | version
  , notificationVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Notification
    where toJSON obj = Data.Aeson.Types.Internal.object ("createdDate" Data.Aeson.Types.ToJSON..= notificationCreatedDate obj : "description" Data.Aeson.Types.ToJSON..= notificationDescription obj : "id" Data.Aeson.Types.ToJSON..= notificationId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= notificationLastModifiedDate obj : "read" Data.Aeson.Types.ToJSON..= notificationRead obj : "title" Data.Aeson.Types.ToJSON..= notificationTitle obj : "version" Data.Aeson.Types.ToJSON..= notificationVersion obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("createdDate" Data.Aeson.Types.ToJSON..= notificationCreatedDate obj) GHC.Base.<> (("description" Data.Aeson.Types.ToJSON..= notificationDescription obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= notificationId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= notificationLastModifiedDate obj) GHC.Base.<> (("read" Data.Aeson.Types.ToJSON..= notificationRead obj) GHC.Base.<> (("title" Data.Aeson.Types.ToJSON..= notificationTitle obj) GHC.Base.<> ("version" Data.Aeson.Types.ToJSON..= notificationVersion obj)))))))
instance Data.Aeson.Types.FromJSON.FromJSON Notification
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Notification" (\obj -> ((((((GHC.Base.pure Notification GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "read")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "title")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version"))
-- | Create a new 'Notification' with all required fields.
mkNotification :: Data.Text.Internal.Text -- ^ 'notificationTitle'
  -> Notification
mkNotification notificationTitle = Notification{notificationCreatedDate = GHC.Maybe.Nothing,
                                                notificationDescription = GHC.Maybe.Nothing,
                                                notificationId = GHC.Maybe.Nothing,
                                                notificationLastModifiedDate = GHC.Maybe.Nothing,
                                                notificationRead = GHC.Maybe.Nothing,
                                                notificationTitle = notificationTitle,
                                                notificationVersion = GHC.Maybe.Nothing}
