-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PartyHabitualExporterLetterOfIntent
module WeclappAPI.Types.PartyHabitualExporterLetterOfIntent where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias
import {-# SOURCE #-} WeclappAPI.Types.OnlyId

-- | Defines the object schema located at @components.schemas.partyHabitualExporterLetterOfIntent@ in the specification.
-- 
-- 
data PartyHabitualExporterLetterOfIntent = PartyHabitualExporterLetterOfIntent {
  -- | automaticallySuggestInInvoice
  partyHabitualExporterLetterOfIntentAutomaticallySuggestInInvoice :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | createdDate
  , partyHabitualExporterLetterOfIntentCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | date
  , partyHabitualExporterLetterOfIntentDate :: GHC.Types.Int
  -- | fromSupplier
  , partyHabitualExporterLetterOfIntentFromSupplier :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | id
  , partyHabitualExporterLetterOfIntentId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | invoices
  , partyHabitualExporterLetterOfIntentInvoices :: (GHC.Maybe.Maybe ([OnlyId]))
  -- | lastModifiedDate
  , partyHabitualExporterLetterOfIntentLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | numberDeclarer
  , partyHabitualExporterLetterOfIntentNumberDeclarer :: Data.Text.Internal.Text
  -- | numberSupplier
  , partyHabitualExporterLetterOfIntentNumberSupplier :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | totalAmount
  , partyHabitualExporterLetterOfIntentTotalAmount :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | type
  , partyHabitualExporterLetterOfIntentType :: PartyHabitualExporterLetterOfIntentType'
  -- | version
  , partyHabitualExporterLetterOfIntentVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PartyHabitualExporterLetterOfIntent
    where toJSON obj = Data.Aeson.Types.Internal.object ("automaticallySuggestInInvoice" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentAutomaticallySuggestInInvoice obj : "createdDate" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentCreatedDate obj : "date" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentDate obj : "fromSupplier" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentFromSupplier obj : "id" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentId obj : "invoices" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentInvoices obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentLastModifiedDate obj : "numberDeclarer" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentNumberDeclarer obj : "numberSupplier" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentNumberSupplier obj : "totalAmount" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentTotalAmount obj : "type" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentType obj : "version" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentVersion obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("automaticallySuggestInInvoice" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentAutomaticallySuggestInInvoice obj) GHC.Base.<> (("createdDate" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentCreatedDate obj) GHC.Base.<> (("date" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentDate obj) GHC.Base.<> (("fromSupplier" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentFromSupplier obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentId obj) GHC.Base.<> (("invoices" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentInvoices obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentLastModifiedDate obj) GHC.Base.<> (("numberDeclarer" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentNumberDeclarer obj) GHC.Base.<> (("numberSupplier" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentNumberSupplier obj) GHC.Base.<> (("totalAmount" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentTotalAmount obj) GHC.Base.<> (("type" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentType obj) GHC.Base.<> ("version" Data.Aeson.Types.ToJSON..= partyHabitualExporterLetterOfIntentVersion obj))))))))))))
instance Data.Aeson.Types.FromJSON.FromJSON PartyHabitualExporterLetterOfIntent
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PartyHabitualExporterLetterOfIntent" (\obj -> (((((((((((GHC.Base.pure PartyHabitualExporterLetterOfIntent GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "automaticallySuggestInInvoice")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "date")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "fromSupplier")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "invoices")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "numberDeclarer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "numberSupplier")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "totalAmount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version"))
-- | Create a new 'PartyHabitualExporterLetterOfIntent' with all required fields.
mkPartyHabitualExporterLetterOfIntent :: GHC.Types.Int -- ^ 'partyHabitualExporterLetterOfIntentDate'
  -> Data.Text.Internal.Text -- ^ 'partyHabitualExporterLetterOfIntentNumberDeclarer'
  -> PartyHabitualExporterLetterOfIntentType' -- ^ 'partyHabitualExporterLetterOfIntentType'
  -> PartyHabitualExporterLetterOfIntent
mkPartyHabitualExporterLetterOfIntent partyHabitualExporterLetterOfIntentDate partyHabitualExporterLetterOfIntentNumberDeclarer partyHabitualExporterLetterOfIntentType = PartyHabitualExporterLetterOfIntent{partyHabitualExporterLetterOfIntentAutomaticallySuggestInInvoice = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentCreatedDate = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentDate = partyHabitualExporterLetterOfIntentDate,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentFromSupplier = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentId = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentInvoices = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentLastModifiedDate = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentNumberDeclarer = partyHabitualExporterLetterOfIntentNumberDeclarer,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentNumberSupplier = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentTotalAmount = GHC.Maybe.Nothing,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentType = partyHabitualExporterLetterOfIntentType,
                                                                                                                                                                                                              partyHabitualExporterLetterOfIntentVersion = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.partyHabitualExporterLetterOfIntent.properties.type@ in the specification.
-- 
-- 
data PartyHabitualExporterLetterOfIntentType' =
   PartyHabitualExporterLetterOfIntentType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PartyHabitualExporterLetterOfIntentType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PartyHabitualExporterLetterOfIntentType'EnumMULTIPLE_ACCOUNTING_EVENTS -- ^ Represents the JSON value @"MULTIPLE_ACCOUNTING_EVENTS"@
  | PartyHabitualExporterLetterOfIntentType'EnumSINGLE_ACCOUNTING_EVENT -- ^ Represents the JSON value @"SINGLE_ACCOUNTING_EVENT"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PartyHabitualExporterLetterOfIntentType'
    where toJSON (PartyHabitualExporterLetterOfIntentType'Other val) = val
          toJSON (PartyHabitualExporterLetterOfIntentType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (PartyHabitualExporterLetterOfIntentType'EnumMULTIPLE_ACCOUNTING_EVENTS) = "MULTIPLE_ACCOUNTING_EVENTS"
          toJSON (PartyHabitualExporterLetterOfIntentType'EnumSINGLE_ACCOUNTING_EVENT) = "SINGLE_ACCOUNTING_EVENT"
instance Data.Aeson.Types.FromJSON.FromJSON PartyHabitualExporterLetterOfIntentType'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "MULTIPLE_ACCOUNTING_EVENTS" -> PartyHabitualExporterLetterOfIntentType'EnumMULTIPLE_ACCOUNTING_EVENTS
                                            | val GHC.Classes.== "SINGLE_ACCOUNTING_EVENT" -> PartyHabitualExporterLetterOfIntentType'EnumSINGLE_ACCOUNTING_EVENT
                                            | GHC.Base.otherwise -> PartyHabitualExporterLetterOfIntentType'Other val)
