-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ProductionOrderStatusHistory
module WeclappAPI.Types.ProductionOrderStatusHistory where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.productionOrderStatusHistory@ in the specification.
-- 
-- 
data ProductionOrderStatusHistory = ProductionOrderStatusHistory {
  -- | status
  productionOrderStatusHistoryStatus :: (GHC.Maybe.Maybe ProductionOrderStatusHistoryStatus')
  -- | statusDate
  , productionOrderStatusHistoryStatusDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | userId
  , productionOrderStatusHistoryUserId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ProductionOrderStatusHistory
    where toJSON obj = Data.Aeson.Types.Internal.object ("status" Data.Aeson.Types.ToJSON..= productionOrderStatusHistoryStatus obj : "statusDate" Data.Aeson.Types.ToJSON..= productionOrderStatusHistoryStatusDate obj : "userId" Data.Aeson.Types.ToJSON..= productionOrderStatusHistoryUserId obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("status" Data.Aeson.Types.ToJSON..= productionOrderStatusHistoryStatus obj) GHC.Base.<> (("statusDate" Data.Aeson.Types.ToJSON..= productionOrderStatusHistoryStatusDate obj) GHC.Base.<> ("userId" Data.Aeson.Types.ToJSON..= productionOrderStatusHistoryUserId obj)))
instance Data.Aeson.Types.FromJSON.FromJSON ProductionOrderStatusHistory
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "ProductionOrderStatusHistory" (\obj -> ((GHC.Base.pure ProductionOrderStatusHistory GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "status")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "statusDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "userId"))
-- | Create a new 'ProductionOrderStatusHistory' with all required fields.
mkProductionOrderStatusHistory :: ProductionOrderStatusHistory
mkProductionOrderStatusHistory = ProductionOrderStatusHistory{productionOrderStatusHistoryStatus = GHC.Maybe.Nothing,
                                                              productionOrderStatusHistoryStatusDate = GHC.Maybe.Nothing,
                                                              productionOrderStatusHistoryUserId = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.productionOrderStatusHistory.properties.status@ in the specification.
-- 
-- 
data ProductionOrderStatusHistoryStatus' =
   ProductionOrderStatusHistoryStatus'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | ProductionOrderStatusHistoryStatus'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | ProductionOrderStatusHistoryStatus'EnumCANCELLED -- ^ Represents the JSON value @"CANCELLED"@
  | ProductionOrderStatusHistoryStatus'EnumCLOSED -- ^ Represents the JSON value @"CLOSED"@
  | ProductionOrderStatusHistoryStatus'EnumDOCUMENTS_PRINTED -- ^ Represents the JSON value @"DOCUMENTS_PRINTED"@
  | ProductionOrderStatusHistoryStatus'EnumENTRY_IN_PROGRESS -- ^ Represents the JSON value @"ENTRY_IN_PROGRESS"@
  | ProductionOrderStatusHistoryStatus'EnumINTERRUPTED -- ^ Represents the JSON value @"INTERRUPTED"@
  | ProductionOrderStatusHistoryStatus'EnumNEW -- ^ Represents the JSON value @"NEW"@
  | ProductionOrderStatusHistoryStatus'EnumSTARTED -- ^ Represents the JSON value @"STARTED"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ProductionOrderStatusHistoryStatus'
    where toJSON (ProductionOrderStatusHistoryStatus'Other val) = val
          toJSON (ProductionOrderStatusHistoryStatus'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (ProductionOrderStatusHistoryStatus'EnumCANCELLED) = "CANCELLED"
          toJSON (ProductionOrderStatusHistoryStatus'EnumCLOSED) = "CLOSED"
          toJSON (ProductionOrderStatusHistoryStatus'EnumDOCUMENTS_PRINTED) = "DOCUMENTS_PRINTED"
          toJSON (ProductionOrderStatusHistoryStatus'EnumENTRY_IN_PROGRESS) = "ENTRY_IN_PROGRESS"
          toJSON (ProductionOrderStatusHistoryStatus'EnumINTERRUPTED) = "INTERRUPTED"
          toJSON (ProductionOrderStatusHistoryStatus'EnumNEW) = "NEW"
          toJSON (ProductionOrderStatusHistoryStatus'EnumSTARTED) = "STARTED"
instance Data.Aeson.Types.FromJSON.FromJSON ProductionOrderStatusHistoryStatus'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "CANCELLED" -> ProductionOrderStatusHistoryStatus'EnumCANCELLED
                                            | val GHC.Classes.== "CLOSED" -> ProductionOrderStatusHistoryStatus'EnumCLOSED
                                            | val GHC.Classes.== "DOCUMENTS_PRINTED" -> ProductionOrderStatusHistoryStatus'EnumDOCUMENTS_PRINTED
                                            | val GHC.Classes.== "ENTRY_IN_PROGRESS" -> ProductionOrderStatusHistoryStatus'EnumENTRY_IN_PROGRESS
                                            | val GHC.Classes.== "INTERRUPTED" -> ProductionOrderStatusHistoryStatus'EnumINTERRUPTED
                                            | val GHC.Classes.== "NEW" -> ProductionOrderStatusHistoryStatus'EnumNEW
                                            | val GHC.Classes.== "STARTED" -> ProductionOrderStatusHistoryStatus'EnumSTARTED
                                            | GHC.Base.otherwise -> ProductionOrderStatusHistoryStatus'Other val)
