module WeclappAPI.Types.PurchaseOrderRequestStatusHistory where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PurchaseOrderRequestStatusHistory
instance Show PurchaseOrderRequestStatusHistory
instance Eq PurchaseOrderRequestStatusHistory
instance FromJSON PurchaseOrderRequestStatusHistory
instance ToJSON PurchaseOrderRequestStatusHistory
data PurchaseOrderRequestStatusHistoryStatus'
instance Show PurchaseOrderRequestStatusHistoryStatus'
instance Eq PurchaseOrderRequestStatusHistoryStatus'
instance FromJSON PurchaseOrderRequestStatusHistoryStatus'
instance ToJSON PurchaseOrderRequestStatusHistoryStatus'
