-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PurchaseOrderStatusHistory
module WeclappAPI.Types.PurchaseOrderStatusHistory where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.purchaseOrderStatusHistory@ in the specification.
-- 
-- 
data PurchaseOrderStatusHistory = PurchaseOrderStatusHistory {
  -- | status
  purchaseOrderStatusHistoryStatus :: (GHC.Maybe.Maybe PurchaseOrderStatusHistoryStatus')
  -- | statusDate
  , purchaseOrderStatusHistoryStatusDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | userId
  , purchaseOrderStatusHistoryUserId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PurchaseOrderStatusHistory
    where toJSON obj = Data.Aeson.Types.Internal.object ("status" Data.Aeson.Types.ToJSON..= purchaseOrderStatusHistoryStatus obj : "statusDate" Data.Aeson.Types.ToJSON..= purchaseOrderStatusHistoryStatusDate obj : "userId" Data.Aeson.Types.ToJSON..= purchaseOrderStatusHistoryUserId obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("status" Data.Aeson.Types.ToJSON..= purchaseOrderStatusHistoryStatus obj) GHC.Base.<> (("statusDate" Data.Aeson.Types.ToJSON..= purchaseOrderStatusHistoryStatusDate obj) GHC.Base.<> ("userId" Data.Aeson.Types.ToJSON..= purchaseOrderStatusHistoryUserId obj)))
instance Data.Aeson.Types.FromJSON.FromJSON PurchaseOrderStatusHistory
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PurchaseOrderStatusHistory" (\obj -> ((GHC.Base.pure PurchaseOrderStatusHistory GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "status")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "statusDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "userId"))
-- | Create a new 'PurchaseOrderStatusHistory' with all required fields.
mkPurchaseOrderStatusHistory :: PurchaseOrderStatusHistory
mkPurchaseOrderStatusHistory = PurchaseOrderStatusHistory{purchaseOrderStatusHistoryStatus = GHC.Maybe.Nothing,
                                                          purchaseOrderStatusHistoryStatusDate = GHC.Maybe.Nothing,
                                                          purchaseOrderStatusHistoryUserId = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.purchaseOrderStatusHistory.properties.status@ in the specification.
-- 
-- 
data PurchaseOrderStatusHistoryStatus' =
   PurchaseOrderStatusHistoryStatus'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PurchaseOrderStatusHistoryStatus'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PurchaseOrderStatusHistoryStatus'EnumCANCELLED -- ^ Represents the JSON value @"CANCELLED"@
  | PurchaseOrderStatusHistoryStatus'EnumCLOSED -- ^ Represents the JSON value @"CLOSED"@
  | PurchaseOrderStatusHistoryStatus'EnumCONFIRMED -- ^ Represents the JSON value @"CONFIRMED"@
  | PurchaseOrderStatusHistoryStatus'EnumNEW -- ^ Represents the JSON value @"NEW"@
  | PurchaseOrderStatusHistoryStatus'EnumORDER_DOCUMENTS_PRINTED -- ^ Represents the JSON value @"ORDER_DOCUMENTS_PRINTED"@
  | PurchaseOrderStatusHistoryStatus'EnumORDER_ENTRY_COMPLETED -- ^ Represents the JSON value @"ORDER_ENTRY_COMPLETED"@
  | PurchaseOrderStatusHistoryStatus'EnumORDER_ENTRY_IN_PROGRESS -- ^ Represents the JSON value @"ORDER_ENTRY_IN_PROGRESS"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PurchaseOrderStatusHistoryStatus'
    where toJSON (PurchaseOrderStatusHistoryStatus'Other val) = val
          toJSON (PurchaseOrderStatusHistoryStatus'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (PurchaseOrderStatusHistoryStatus'EnumCANCELLED) = "CANCELLED"
          toJSON (PurchaseOrderStatusHistoryStatus'EnumCLOSED) = "CLOSED"
          toJSON (PurchaseOrderStatusHistoryStatus'EnumCONFIRMED) = "CONFIRMED"
          toJSON (PurchaseOrderStatusHistoryStatus'EnumNEW) = "NEW"
          toJSON (PurchaseOrderStatusHistoryStatus'EnumORDER_DOCUMENTS_PRINTED) = "ORDER_DOCUMENTS_PRINTED"
          toJSON (PurchaseOrderStatusHistoryStatus'EnumORDER_ENTRY_COMPLETED) = "ORDER_ENTRY_COMPLETED"
          toJSON (PurchaseOrderStatusHistoryStatus'EnumORDER_ENTRY_IN_PROGRESS) = "ORDER_ENTRY_IN_PROGRESS"
instance Data.Aeson.Types.FromJSON.FromJSON PurchaseOrderStatusHistoryStatus'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "CANCELLED" -> PurchaseOrderStatusHistoryStatus'EnumCANCELLED
                                            | val GHC.Classes.== "CLOSED" -> PurchaseOrderStatusHistoryStatus'EnumCLOSED
                                            | val GHC.Classes.== "CONFIRMED" -> PurchaseOrderStatusHistoryStatus'EnumCONFIRMED
                                            | val GHC.Classes.== "NEW" -> PurchaseOrderStatusHistoryStatus'EnumNEW
                                            | val GHC.Classes.== "ORDER_DOCUMENTS_PRINTED" -> PurchaseOrderStatusHistoryStatus'EnumORDER_DOCUMENTS_PRINTED
                                            | val GHC.Classes.== "ORDER_ENTRY_COMPLETED" -> PurchaseOrderStatusHistoryStatus'EnumORDER_ENTRY_COMPLETED
                                            | val GHC.Classes.== "ORDER_ENTRY_IN_PROGRESS" -> PurchaseOrderStatusHistoryStatus'EnumORDER_ENTRY_IN_PROGRESS
                                            | GHC.Base.otherwise -> PurchaseOrderStatusHistoryStatus'Other val)
