-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema QuotationStatusHistory
module WeclappAPI.Types.QuotationStatusHistory where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.quotationStatusHistory@ in the specification.
-- 
-- 
data QuotationStatusHistory = QuotationStatusHistory {
  -- | status
  quotationStatusHistoryStatus :: (GHC.Maybe.Maybe QuotationStatusHistoryStatus')
  -- | statusDate
  , quotationStatusHistoryStatusDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | userId
  , quotationStatusHistoryUserId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON QuotationStatusHistory
    where toJSON obj = Data.Aeson.Types.Internal.object ("status" Data.Aeson.Types.ToJSON..= quotationStatusHistoryStatus obj : "statusDate" Data.Aeson.Types.ToJSON..= quotationStatusHistoryStatusDate obj : "userId" Data.Aeson.Types.ToJSON..= quotationStatusHistoryUserId obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("status" Data.Aeson.Types.ToJSON..= quotationStatusHistoryStatus obj) GHC.Base.<> (("statusDate" Data.Aeson.Types.ToJSON..= quotationStatusHistoryStatusDate obj) GHC.Base.<> ("userId" Data.Aeson.Types.ToJSON..= quotationStatusHistoryUserId obj)))
instance Data.Aeson.Types.FromJSON.FromJSON QuotationStatusHistory
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "QuotationStatusHistory" (\obj -> ((GHC.Base.pure QuotationStatusHistory GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "status")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "statusDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "userId"))
-- | Create a new 'QuotationStatusHistory' with all required fields.
mkQuotationStatusHistory :: QuotationStatusHistory
mkQuotationStatusHistory = QuotationStatusHistory{quotationStatusHistoryStatus = GHC.Maybe.Nothing,
                                                  quotationStatusHistoryStatusDate = GHC.Maybe.Nothing,
                                                  quotationStatusHistoryUserId = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.quotationStatusHistory.properties.status@ in the specification.
-- 
-- 
data QuotationStatusHistoryStatus' =
   QuotationStatusHistoryStatus'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | QuotationStatusHistoryStatus'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | QuotationStatusHistoryStatus'EnumACCEPTED -- ^ Represents the JSON value @"ACCEPTED"@
  | QuotationStatusHistoryStatus'EnumCLOSED -- ^ Represents the JSON value @"CLOSED"@
  | QuotationStatusHistoryStatus'EnumINQUIRED -- ^ Represents the JSON value @"INQUIRED"@
  | QuotationStatusHistoryStatus'EnumOPEN -- ^ Represents the JSON value @"OPEN"@
  | QuotationStatusHistoryStatus'EnumREJECTED -- ^ Represents the JSON value @"REJECTED"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON QuotationStatusHistoryStatus'
    where toJSON (QuotationStatusHistoryStatus'Other val) = val
          toJSON (QuotationStatusHistoryStatus'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (QuotationStatusHistoryStatus'EnumACCEPTED) = "ACCEPTED"
          toJSON (QuotationStatusHistoryStatus'EnumCLOSED) = "CLOSED"
          toJSON (QuotationStatusHistoryStatus'EnumINQUIRED) = "INQUIRED"
          toJSON (QuotationStatusHistoryStatus'EnumOPEN) = "OPEN"
          toJSON (QuotationStatusHistoryStatus'EnumREJECTED) = "REJECTED"
instance Data.Aeson.Types.FromJSON.FromJSON QuotationStatusHistoryStatus'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "ACCEPTED" -> QuotationStatusHistoryStatus'EnumACCEPTED
                                            | val GHC.Classes.== "CLOSED" -> QuotationStatusHistoryStatus'EnumCLOSED
                                            | val GHC.Classes.== "INQUIRED" -> QuotationStatusHistoryStatus'EnumINQUIRED
                                            | val GHC.Classes.== "OPEN" -> QuotationStatusHistoryStatus'EnumOPEN
                                            | val GHC.Classes.== "REJECTED" -> QuotationStatusHistoryStatus'EnumREJECTED
                                            | GHC.Base.otherwise -> QuotationStatusHistoryStatus'Other val)
