-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema User
module WeclappAPI.Types.User where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias
import {-# SOURCE #-} WeclappAPI.Types.CustomAttribute

-- | Defines the object schema located at @components.schemas.user@ in the specification.
-- 
-- 
data User = User {
  -- | birthDate
  userBirthDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | createdDate
  , userCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | customAttributes
  , userCustomAttributes :: (GHC.Maybe.Maybe ([CustomAttribute]))
  -- | email
  , userEmail :: Data.Text.Internal.Text
  -- | faxNumber
  , userFaxNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | firstName
  , userFirstName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id
  , userId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | imageId
  , userImageId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , userLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | lastName
  , userLastName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | mobilePhoneNumber
  , userMobilePhoneNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | phoneNumber
  , userPhoneNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | status
  , userStatus :: (GHC.Maybe.Maybe UserStatus')
  -- | username
  , userUsername :: Data.Text.Internal.Text
  -- | version
  , userVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON User
    where toJSON obj = Data.Aeson.Types.Internal.object ("birthDate" Data.Aeson.Types.ToJSON..= userBirthDate obj : "createdDate" Data.Aeson.Types.ToJSON..= userCreatedDate obj : "customAttributes" Data.Aeson.Types.ToJSON..= userCustomAttributes obj : "email" Data.Aeson.Types.ToJSON..= userEmail obj : "faxNumber" Data.Aeson.Types.ToJSON..= userFaxNumber obj : "firstName" Data.Aeson.Types.ToJSON..= userFirstName obj : "id" Data.Aeson.Types.ToJSON..= userId obj : "imageId" Data.Aeson.Types.ToJSON..= userImageId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= userLastModifiedDate obj : "lastName" Data.Aeson.Types.ToJSON..= userLastName obj : "mobilePhoneNumber" Data.Aeson.Types.ToJSON..= userMobilePhoneNumber obj : "phoneNumber" Data.Aeson.Types.ToJSON..= userPhoneNumber obj : "status" Data.Aeson.Types.ToJSON..= userStatus obj : "username" Data.Aeson.Types.ToJSON..= userUsername obj : "version" Data.Aeson.Types.ToJSON..= userVersion obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("birthDate" Data.Aeson.Types.ToJSON..= userBirthDate obj) GHC.Base.<> (("createdDate" Data.Aeson.Types.ToJSON..= userCreatedDate obj) GHC.Base.<> (("customAttributes" Data.Aeson.Types.ToJSON..= userCustomAttributes obj) GHC.Base.<> (("email" Data.Aeson.Types.ToJSON..= userEmail obj) GHC.Base.<> (("faxNumber" Data.Aeson.Types.ToJSON..= userFaxNumber obj) GHC.Base.<> (("firstName" Data.Aeson.Types.ToJSON..= userFirstName obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= userId obj) GHC.Base.<> (("imageId" Data.Aeson.Types.ToJSON..= userImageId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= userLastModifiedDate obj) GHC.Base.<> (("lastName" Data.Aeson.Types.ToJSON..= userLastName obj) GHC.Base.<> (("mobilePhoneNumber" Data.Aeson.Types.ToJSON..= userMobilePhoneNumber obj) GHC.Base.<> (("phoneNumber" Data.Aeson.Types.ToJSON..= userPhoneNumber obj) GHC.Base.<> (("status" Data.Aeson.Types.ToJSON..= userStatus obj) GHC.Base.<> (("username" Data.Aeson.Types.ToJSON..= userUsername obj) GHC.Base.<> ("version" Data.Aeson.Types.ToJSON..= userVersion obj)))))))))))))))
instance Data.Aeson.Types.FromJSON.FromJSON User
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "User" (\obj -> ((((((((((((((GHC.Base.pure User GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "birthDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "customAttributes")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "email")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "faxNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "firstName")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "imageId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastName")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "mobilePhoneNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "phoneNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "status")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "username")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version"))
-- | Create a new 'User' with all required fields.
mkUser :: Data.Text.Internal.Text -- ^ 'userEmail'
  -> Data.Text.Internal.Text -- ^ 'userUsername'
  -> User
mkUser userEmail userUsername = User{userBirthDate = GHC.Maybe.Nothing,
                                     userCreatedDate = GHC.Maybe.Nothing,
                                     userCustomAttributes = GHC.Maybe.Nothing,
                                     userEmail = userEmail,
                                     userFaxNumber = GHC.Maybe.Nothing,
                                     userFirstName = GHC.Maybe.Nothing,
                                     userId = GHC.Maybe.Nothing,
                                     userImageId = GHC.Maybe.Nothing,
                                     userLastModifiedDate = GHC.Maybe.Nothing,
                                     userLastName = GHC.Maybe.Nothing,
                                     userMobilePhoneNumber = GHC.Maybe.Nothing,
                                     userPhoneNumber = GHC.Maybe.Nothing,
                                     userStatus = GHC.Maybe.Nothing,
                                     userUsername = userUsername,
                                     userVersion = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.user.properties.status@ in the specification.
-- 
-- 
data UserStatus' =
   UserStatus'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | UserStatus'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | UserStatus'EnumACTIVE -- ^ Represents the JSON value @"ACTIVE"@
  | UserStatus'EnumBLOCKED -- ^ Represents the JSON value @"BLOCKED"@
  | UserStatus'EnumDEPARTURE -- ^ Represents the JSON value @"DEPARTURE"@
  | UserStatus'EnumNOT_ACTIVE -- ^ Represents the JSON value @"NOT_ACTIVE"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON UserStatus'
    where toJSON (UserStatus'Other val) = val
          toJSON (UserStatus'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (UserStatus'EnumACTIVE) = "ACTIVE"
          toJSON (UserStatus'EnumBLOCKED) = "BLOCKED"
          toJSON (UserStatus'EnumDEPARTURE) = "DEPARTURE"
          toJSON (UserStatus'EnumNOT_ACTIVE) = "NOT_ACTIVE"
instance Data.Aeson.Types.FromJSON.FromJSON UserStatus'
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "ACTIVE" -> UserStatus'EnumACTIVE
                                            | val GHC.Classes.== "BLOCKED" -> UserStatus'EnumBLOCKED
                                            | val GHC.Classes.== "DEPARTURE" -> UserStatus'EnumDEPARTURE
                                            | val GHC.Classes.== "NOT_ACTIVE" -> UserStatus'EnumNOT_ACTIVE
                                            | GHC.Base.otherwise -> UserStatus'Other val)
