-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema VariantArticleVariant
module WeclappAPI.Types.VariantArticleVariant where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias
import {-# SOURCE #-} WeclappAPI.Types.OnlyId

-- | Defines the object schema located at @components.schemas.variantArticleVariant@ in the specification.
-- 
-- 
data VariantArticleVariant = VariantArticleVariant {
  -- | articleId
  variantArticleVariantArticleId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | articleNumber
  , variantArticleVariantArticleNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | attributeOptions
  , variantArticleVariantAttributeOptions :: (GHC.Maybe.Maybe ([OnlyId]))
  -- | createdDate
  , variantArticleVariantCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | id
  , variantArticleVariantId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , variantArticleVariantLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | variantArticleId
  , variantArticleVariantVariantArticleId :: Data.Text.Internal.Text
  -- | variantArticleNumber
  , variantArticleVariantVariantArticleNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | version
  , variantArticleVariantVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON VariantArticleVariant
    where toJSON obj = Data.Aeson.Types.Internal.object ("articleId" Data.Aeson.Types.ToJSON..= variantArticleVariantArticleId obj : "articleNumber" Data.Aeson.Types.ToJSON..= variantArticleVariantArticleNumber obj : "attributeOptions" Data.Aeson.Types.ToJSON..= variantArticleVariantAttributeOptions obj : "createdDate" Data.Aeson.Types.ToJSON..= variantArticleVariantCreatedDate obj : "id" Data.Aeson.Types.ToJSON..= variantArticleVariantId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= variantArticleVariantLastModifiedDate obj : "variantArticleId" Data.Aeson.Types.ToJSON..= variantArticleVariantVariantArticleId obj : "variantArticleNumber" Data.Aeson.Types.ToJSON..= variantArticleVariantVariantArticleNumber obj : "version" Data.Aeson.Types.ToJSON..= variantArticleVariantVersion obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("articleId" Data.Aeson.Types.ToJSON..= variantArticleVariantArticleId obj) GHC.Base.<> (("articleNumber" Data.Aeson.Types.ToJSON..= variantArticleVariantArticleNumber obj) GHC.Base.<> (("attributeOptions" Data.Aeson.Types.ToJSON..= variantArticleVariantAttributeOptions obj) GHC.Base.<> (("createdDate" Data.Aeson.Types.ToJSON..= variantArticleVariantCreatedDate obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= variantArticleVariantId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= variantArticleVariantLastModifiedDate obj) GHC.Base.<> (("variantArticleId" Data.Aeson.Types.ToJSON..= variantArticleVariantVariantArticleId obj) GHC.Base.<> (("variantArticleNumber" Data.Aeson.Types.ToJSON..= variantArticleVariantVariantArticleNumber obj) GHC.Base.<> ("version" Data.Aeson.Types.ToJSON..= variantArticleVariantVersion obj)))))))))
instance Data.Aeson.Types.FromJSON.FromJSON VariantArticleVariant
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "VariantArticleVariant" (\obj -> ((((((((GHC.Base.pure VariantArticleVariant GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "articleId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "articleNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "attributeOptions")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "variantArticleId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "variantArticleNumber")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version"))
-- | Create a new 'VariantArticleVariant' with all required fields.
mkVariantArticleVariant :: Data.Text.Internal.Text -- ^ 'variantArticleVariantVariantArticleId'
  -> VariantArticleVariant
mkVariantArticleVariant variantArticleVariantVariantArticleId = VariantArticleVariant{variantArticleVariantArticleId = GHC.Maybe.Nothing,
                                                                                      variantArticleVariantArticleNumber = GHC.Maybe.Nothing,
                                                                                      variantArticleVariantAttributeOptions = GHC.Maybe.Nothing,
                                                                                      variantArticleVariantCreatedDate = GHC.Maybe.Nothing,
                                                                                      variantArticleVariantId = GHC.Maybe.Nothing,
                                                                                      variantArticleVariantLastModifiedDate = GHC.Maybe.Nothing,
                                                                                      variantArticleVariantVariantArticleId = variantArticleVariantVariantArticleId,
                                                                                      variantArticleVariantVariantArticleNumber = GHC.Maybe.Nothing,
                                                                                      variantArticleVariantVersion = GHC.Maybe.Nothing}
