-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema WarehouseLevel
module WeclappAPI.Types.WarehouseLevel where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified WeclappAPI.Common
import WeclappAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.warehouseLevel@ in the specification.
-- 
-- 
data WarehouseLevel = WarehouseLevel {
  -- | barcode
  warehouseLevelBarcode :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | createdDate
  , warehouseLevelCreatedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | deleted
  , warehouseLevelDeleted :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | forPicking
  , warehouseLevelForPicking :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | height
  , warehouseLevelHeight :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id
  , warehouseLevelId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | lastModifiedDate
  , warehouseLevelLastModifiedDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | length
  , warehouseLevelLength :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | name
  , warehouseLevelName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | parentLevelId
  , warehouseLevelParentLevelId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | stockable
  , warehouseLevelStockable :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | version
  , warehouseLevelVersion :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | warehouseId
  , warehouseLevelWarehouseId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | weight
  , warehouseLevelWeight :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | width
  , warehouseLevelWidth :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON WarehouseLevel
    where toJSON obj = Data.Aeson.Types.Internal.object ("barcode" Data.Aeson.Types.ToJSON..= warehouseLevelBarcode obj : "createdDate" Data.Aeson.Types.ToJSON..= warehouseLevelCreatedDate obj : "deleted" Data.Aeson.Types.ToJSON..= warehouseLevelDeleted obj : "forPicking" Data.Aeson.Types.ToJSON..= warehouseLevelForPicking obj : "height" Data.Aeson.Types.ToJSON..= warehouseLevelHeight obj : "id" Data.Aeson.Types.ToJSON..= warehouseLevelId obj : "lastModifiedDate" Data.Aeson.Types.ToJSON..= warehouseLevelLastModifiedDate obj : "length" Data.Aeson.Types.ToJSON..= warehouseLevelLength obj : "name" Data.Aeson.Types.ToJSON..= warehouseLevelName obj : "parentLevelId" Data.Aeson.Types.ToJSON..= warehouseLevelParentLevelId obj : "stockable" Data.Aeson.Types.ToJSON..= warehouseLevelStockable obj : "version" Data.Aeson.Types.ToJSON..= warehouseLevelVersion obj : "warehouseId" Data.Aeson.Types.ToJSON..= warehouseLevelWarehouseId obj : "weight" Data.Aeson.Types.ToJSON..= warehouseLevelWeight obj : "width" Data.Aeson.Types.ToJSON..= warehouseLevelWidth obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("barcode" Data.Aeson.Types.ToJSON..= warehouseLevelBarcode obj) GHC.Base.<> (("createdDate" Data.Aeson.Types.ToJSON..= warehouseLevelCreatedDate obj) GHC.Base.<> (("deleted" Data.Aeson.Types.ToJSON..= warehouseLevelDeleted obj) GHC.Base.<> (("forPicking" Data.Aeson.Types.ToJSON..= warehouseLevelForPicking obj) GHC.Base.<> (("height" Data.Aeson.Types.ToJSON..= warehouseLevelHeight obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= warehouseLevelId obj) GHC.Base.<> (("lastModifiedDate" Data.Aeson.Types.ToJSON..= warehouseLevelLastModifiedDate obj) GHC.Base.<> (("length" Data.Aeson.Types.ToJSON..= warehouseLevelLength obj) GHC.Base.<> (("name" Data.Aeson.Types.ToJSON..= warehouseLevelName obj) GHC.Base.<> (("parentLevelId" Data.Aeson.Types.ToJSON..= warehouseLevelParentLevelId obj) GHC.Base.<> (("stockable" Data.Aeson.Types.ToJSON..= warehouseLevelStockable obj) GHC.Base.<> (("version" Data.Aeson.Types.ToJSON..= warehouseLevelVersion obj) GHC.Base.<> (("warehouseId" Data.Aeson.Types.ToJSON..= warehouseLevelWarehouseId obj) GHC.Base.<> (("weight" Data.Aeson.Types.ToJSON..= warehouseLevelWeight obj) GHC.Base.<> ("width" Data.Aeson.Types.ToJSON..= warehouseLevelWidth obj)))))))))))))))
instance Data.Aeson.Types.FromJSON.FromJSON WarehouseLevel
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "WarehouseLevel" (\obj -> ((((((((((((((GHC.Base.pure WarehouseLevel GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "barcode")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "createdDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "deleted")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "forPicking")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "height")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "lastModifiedDate")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "length")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "parentLevelId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "stockable")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "version")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "warehouseId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "weight")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "width"))
-- | Create a new 'WarehouseLevel' with all required fields.
mkWarehouseLevel :: WarehouseLevel
mkWarehouseLevel = WarehouseLevel{warehouseLevelBarcode = GHC.Maybe.Nothing,
                                  warehouseLevelCreatedDate = GHC.Maybe.Nothing,
                                  warehouseLevelDeleted = GHC.Maybe.Nothing,
                                  warehouseLevelForPicking = GHC.Maybe.Nothing,
                                  warehouseLevelHeight = GHC.Maybe.Nothing,
                                  warehouseLevelId = GHC.Maybe.Nothing,
                                  warehouseLevelLastModifiedDate = GHC.Maybe.Nothing,
                                  warehouseLevelLength = GHC.Maybe.Nothing,
                                  warehouseLevelName = GHC.Maybe.Nothing,
                                  warehouseLevelParentLevelId = GHC.Maybe.Nothing,
                                  warehouseLevelStockable = GHC.Maybe.Nothing,
                                  warehouseLevelVersion = GHC.Maybe.Nothing,
                                  warehouseLevelWarehouseId = GHC.Maybe.Nothing,
                                  warehouseLevelWeight = GHC.Maybe.Nothing,
                                  warehouseLevelWidth = GHC.Maybe.Nothing}
