module WeclappAPI.Types.WarehouseStockMovement where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data WarehouseStockMovement
instance Show WarehouseStockMovement
instance Eq WarehouseStockMovement
instance FromJSON WarehouseStockMovement
instance ToJSON WarehouseStockMovement
data WarehouseStockMovementStockMovementType'
instance Show WarehouseStockMovementStockMovementType'
instance Eq WarehouseStockMovementStockMovementType'
instance FromJSON WarehouseStockMovementStockMovementType'
instance ToJSON WarehouseStockMovementStockMovementType'
