-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation get_comment
module WeclappAPI.Operations.Get_comment where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified WeclappAPI.Common
import WeclappAPI.Types

-- | > GET /comment
-- 
-- query comment
get_comment :: forall m . WeclappAPI.Common.MonadHTTP m => Get_commentParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> WeclappAPI.Common.ClientT m (Network.HTTP.Client.Types.Response Get_commentResponse) -- ^ Monadic computation which returns the result of the operation
get_comment parameters = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either Get_commentResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_commentResponse200 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                          Get_commentResponseBody200)
                                                                                                                                                               | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (WeclappAPI.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/comment") [WeclappAPI.Common.QueryParameter (Data.Text.pack "page") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPage parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                           WeclappAPI.Common.QueryParameter (Data.Text.pack "pageSize") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPageSize parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                           WeclappAPI.Common.QueryParameter (Data.Text.pack "sort") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQuerySort parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                           WeclappAPI.Common.QueryParameter (Data.Text.pack "entityId") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityId parameters)) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                           WeclappAPI.Common.QueryParameter (Data.Text.pack "entityName") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityName parameters)) (Data.Text.pack "form") GHC.Types.False])
-- | Defines the object schema located at @paths.\/comment.GET.parameters@ in the specification.
-- 
-- 
data Get_commentParameters = Get_commentParameters {
  -- | queryEntityId: Represents the parameter named \'entityId\'
  get_commentParametersQueryEntityId :: Data.Text.Internal.Text
  -- | queryEntityName: Represents the parameter named \'entityName\'
  , get_commentParametersQueryEntityName :: Data.Text.Internal.Text
  -- | queryPage: Represents the parameter named \'page\'
  , get_commentParametersQueryPage :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | queryPageSize: Represents the parameter named \'pageSize\'
  , get_commentParametersQueryPageSize :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | querySort: Represents the parameter named \'sort\'
  , get_commentParametersQuerySort :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_commentParameters
    where toJSON obj = Data.Aeson.Types.Internal.object ("queryEntityId" Data.Aeson.Types.ToJSON..= get_commentParametersQueryEntityId obj : "queryEntityName" Data.Aeson.Types.ToJSON..= get_commentParametersQueryEntityName obj : "queryPage" Data.Aeson.Types.ToJSON..= get_commentParametersQueryPage obj : "queryPageSize" Data.Aeson.Types.ToJSON..= get_commentParametersQueryPageSize obj : "querySort" Data.Aeson.Types.ToJSON..= get_commentParametersQuerySort obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("queryEntityId" Data.Aeson.Types.ToJSON..= get_commentParametersQueryEntityId obj) GHC.Base.<> (("queryEntityName" Data.Aeson.Types.ToJSON..= get_commentParametersQueryEntityName obj) GHC.Base.<> (("queryPage" Data.Aeson.Types.ToJSON..= get_commentParametersQueryPage obj) GHC.Base.<> (("queryPageSize" Data.Aeson.Types.ToJSON..= get_commentParametersQueryPageSize obj) GHC.Base.<> ("querySort" Data.Aeson.Types.ToJSON..= get_commentParametersQuerySort obj)))))
instance Data.Aeson.Types.FromJSON.FromJSON Get_commentParameters
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Get_commentParameters" (\obj -> ((((GHC.Base.pure Get_commentParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "queryEntityId")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "queryEntityName")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "queryPage")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "queryPageSize")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "querySort"))
-- | Create a new 'Get_commentParameters' with all required fields.
mkGet_commentParameters :: Data.Text.Internal.Text -- ^ 'get_commentParametersQueryEntityId'
  -> Data.Text.Internal.Text -- ^ 'get_commentParametersQueryEntityName'
  -> Get_commentParameters
mkGet_commentParameters get_commentParametersQueryEntityId get_commentParametersQueryEntityName = Get_commentParameters{get_commentParametersQueryEntityId = get_commentParametersQueryEntityId,
                                                                                                                        get_commentParametersQueryEntityName = get_commentParametersQueryEntityName,
                                                                                                                        get_commentParametersQueryPage = GHC.Maybe.Nothing,
                                                                                                                        get_commentParametersQueryPageSize = GHC.Maybe.Nothing,
                                                                                                                        get_commentParametersQuerySort = GHC.Maybe.Nothing}
-- | Represents a response of the operation 'get_comment'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Get_commentResponseError' is used.
data Get_commentResponse =
   Get_commentResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | Get_commentResponse200 Get_commentResponseBody200 -- ^ comment response
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | Defines the object schema located at @paths.\/comment.GET.responses.200.content.application\/json.schema@ in the specification.
-- 
-- 
data Get_commentResponseBody200 = Get_commentResponseBody200 {
  -- | result
  get_commentResponseBody200Result :: (GHC.Maybe.Maybe ([Comment]))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Get_commentResponseBody200
    where toJSON obj = Data.Aeson.Types.Internal.object ("result" Data.Aeson.Types.ToJSON..= get_commentResponseBody200Result obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("result" Data.Aeson.Types.ToJSON..= get_commentResponseBody200Result obj)
instance Data.Aeson.Types.FromJSON.FromJSON Get_commentResponseBody200
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Get_commentResponseBody200" (\obj -> GHC.Base.pure Get_commentResponseBody200 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "result"))
-- | Create a new 'Get_commentResponseBody200' with all required fields.
mkGet_commentResponseBody200 :: Get_commentResponseBody200
mkGet_commentResponseBody200 = Get_commentResponseBody200{get_commentResponseBody200Result = GHC.Maybe.Nothing}
-- | > GET /comment
-- 
-- The same as 'get_comment' but accepts an explicit configuration.
get_commentWithConfiguration :: forall m . WeclappAPI.Common.MonadHTTP m => WeclappAPI.Common.Configuration -- ^ The configuration to use in the request
  -> Get_commentParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Get_commentResponse) -- ^ Monadic computation which returns the result of the operation
get_commentWithConfiguration config
                             parameters = GHC.Base.fmap (\response_2 -> GHC.Base.fmap (Data.Either.either Get_commentResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Get_commentResponse200 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                           Get_commentResponseBody200)
                                                                                                                                                                                | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_2) response_2) (WeclappAPI.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/comment") [WeclappAPI.Common.QueryParameter (Data.Text.pack "page") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPage parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "pageSize") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPageSize parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "sort") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQuerySort parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "entityId") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityId parameters)) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                                                                                                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "entityName") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityName parameters)) (Data.Text.pack "form") GHC.Types.False])
-- | > GET /comment
-- 
-- The same as 'get_comment' but returns the raw 'Data.ByteString.Char8.ByteString'.
get_commentRaw :: forall m . WeclappAPI.Common.MonadHTTP m => Get_commentParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> WeclappAPI.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
get_commentRaw parameters = GHC.Base.id (WeclappAPI.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/comment") [WeclappAPI.Common.QueryParameter (Data.Text.pack "page") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPage parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "pageSize") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPageSize parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "sort") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQuerySort parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "entityId") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityId parameters)) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                  WeclappAPI.Common.QueryParameter (Data.Text.pack "entityName") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityName parameters)) (Data.Text.pack "form") GHC.Types.False])
-- | > GET /comment
-- 
-- The same as 'get_comment' but accepts an explicit configuration and returns the raw 'Data.ByteString.Char8.ByteString'.
get_commentWithConfigurationRaw :: forall m . WeclappAPI.Common.MonadHTTP m => WeclappAPI.Common.Configuration -- ^ The configuration to use in the request
  -> Get_commentParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
get_commentWithConfigurationRaw config
                                parameters = GHC.Base.id (WeclappAPI.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/comment") [WeclappAPI.Common.QueryParameter (Data.Text.pack "page") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPage parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                         WeclappAPI.Common.QueryParameter (Data.Text.pack "pageSize") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQueryPageSize parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                         WeclappAPI.Common.QueryParameter (Data.Text.pack "sort") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> get_commentParametersQuerySort parameters) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                         WeclappAPI.Common.QueryParameter (Data.Text.pack "entityId") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityId parameters)) (Data.Text.pack "form") GHC.Types.False,
                                                                                                                                                                                         WeclappAPI.Common.QueryParameter (Data.Text.pack "entityName") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (get_commentParametersQueryEntityName parameters)) (Data.Text.pack "form") GHC.Types.False])
